import { Montserrat } from "next/font/google";
import "@/app/reset.css";
import "@/app/animations.css";
import "@/app/globals.css";
import "@/app/media.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Adolex",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
